"""agged teaher name

Revision ID: b989f8385fa8
Revises: 53aeed0347c2
Create Date: 2024-10-13 23:16:28.710015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b989f8385fa8'
down_revision: Union[str, None] = '53aeed0347c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_emails', sa.Column('teacher_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_emails', 'teacher_name')
    # ### end Alembic commands ###
